### ISSUE TITLE
Issue with vendor prefixed aligned CSS rules

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/detect-indent#2]
``` css
#leaflet {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    -webkit-box-shadow: inset -5px -5px 5px rgba(0, 0, 0, 0.6);
       -moz-box-shadow: inset -5px -5px 5px rgba(0, 0, 0, 0.6);
            box-shadow: inset -5px -5px 5px rgba(0, 0, 0, 0.6);
}
```

It currently detects the indentation to 1 space.
